//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoSalonDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korisnik
    {
        public Korisnik()
        {
            this.Komentars = new HashSet<Komentar>();
            this.Ocenas = new HashSet<Ocena>();
        }
    
        public long Id { get; set; }
        public string KorisnickoIme { get; set; }
        public string Lozinka { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Tip { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<Komentar> Komentars { get; set; }
        public virtual ICollection<Ocena> Ocenas { get; set; }
    }
}
