//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoSalonDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model
    {
        public Model()
        {
            this.Komentars = new HashSet<Komentar>();
            this.Ocenas = new HashSet<Ocena>();
        }
    
        public long Id { get; set; }
        public string NazivModela { get; set; }
        public int Motor { get; set; }
        public int Snaga { get; set; }
        public int MaksimalnaBrzina { get; set; }
        public double ProsecnaPotrosnja { get; set; }
        public string Slika { get; set; }
        public string Tip { get; set; }
        public string Status { get; set; }
        public double ProsecnaOcena { get; set; }
        public long IdProizvodjaca { get; set; }
    
        public virtual ICollection<Komentar> Komentars { get; set; }
        public virtual Proizvodjac Proizvodjac { get; set; }
        public virtual ICollection<Ocena> Ocenas { get; set; }
    }
}
