//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoSalonDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ocena
    {
        public long Id { get; set; }
        public long IdModela { get; set; }
        public long IdKorisnika { get; set; }
        public int Vrednost { get; set; }
        public string Status { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual Model Model { get; set; }
    }
}
