//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoSalonDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proizvodjac
    {
        public Proizvodjac()
        {
            this.Models = new HashSet<Model>();
        }
    
        public long Id { get; set; }
        public string NazivProizvodjaca { get; set; }
        public string Tip { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<Model> Models { get; set; }
    }
}
